# Generated by Django 5.1.7 on 2025-03-21 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sidebar',
            name='display_type',
        ),
        migrations.AddField(
            model_name='sidebar',
            name='browse_options',
            field=models.PositiveIntegerField(choices=[(1, 'HTML'), (2, '最新文章'), (3, '最热文章'), (4, '最近评论')], default=1, verbose_name='查看选项'),
        ),
    ]
